### ISSUE TITLE
enhancement request

### ISSUE THREAD

**Issue by simonmcnair** [bertholdm/TextDiff#1]
Hi,
I'm loving your efforts, thank you.

I've been trying to use this to try and reconcile ebooks with spelling mistakes etc, and have found the output difficult to understand as it shows differences where there are no apparent differences.

The HTML view works well for me, but it would be nice to have an option to remove identical lines, so you can see just the differences in the html view.

Thanks again, it's a great plugin.

**Comment by bertholdm** [comment]
Nice that the plugin is also useful for others.  Hiding the identical rows as option is on the to-do list.  The highlighting of the differences makes the Python difflib.  I just slightly modify the returned HTML and CSS.

**Comment by bertholdm** [comment]
> it would be nice to have an option to remove identical lines

Now available in Version 1.2.0 (with the option to display some context lines).
Have fun!
